export const ACTION_TYPES = {
  SET_CURRENT_CATEGORY: 'SET_CURRENT_CATEGORY',
  LOAD_MORE: 'LOAD_MORE',
  RELOAD_PAGE: 'RELOAD_PAGE',
  ADD_CANCEL_TOKEN: 'ADD_CANCEL_TOKEN',
  CANCEL_PENDING_REQUESTS: 'CANCEL_PENDING_REQUESTS',
};
